# Generated by Django 5.2.4 on 2025-07-04 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre de la empresa')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('stage', models.CharField(choices=[('PS', 'Pre-seed'), ('SEED', 'Seed'), ('SA', 'Serie A'), ('SB', 'Serie B'), ('SC', 'Serie C'), ('PYME', 'Pequeño Negocio'), ('ENT', 'Enterprise')], default='SA', max_length=10, verbose_name='Etapa de la empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nombre completo')),
                ('role', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rol o cargo')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='Perfil de LinkedIn')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentors', to='internships.companies', verbose_name='Empresa del mentor')),
            ],
        ),
        migrations.CreateModel(
            name='InternshipOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255, verbose_name='Posición')),
                ('type_of_job', models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time'), ('PR', 'Project-Based')], max_length=2, verbose_name='Tipo de oportunidad')),
                ('duration', models.CharField(max_length=100, verbose_name='Duración')),
                ('date_limit', models.DateField(verbose_name='Fecha límite')),
                ('brief_description', models.TextField(verbose_name='Descripción')),
                ('location', models.CharField(max_length=255, verbose_name='País / Localidad')),
                ('ai_recommendation', models.TextField(blank=True, null=True, verbose_name='Recomendaciones generadas por IA')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('mentors', models.ManyToManyField(blank=True, to='internships.mentor', verbose_name='Mentor')),
            ],
        ),
    ]
