# Generated by Django 5.2.4 on 2025-07-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='industry',
            field=models.CharField(choices=[('WEB3', 'Web3 & Blockchain'), ('FIN', 'Financial Services'), ('ENT_SOFT', 'Enterprise Software'), ('HEALTH', 'Healthcare & Biotech'), ('EDU', 'Education & EdTech'), ('ECOMM', 'E-commerce & Retail'), ('AI_ML', 'Artificial Intelligence & Machine Learning'), ('MOBILITY', 'Mobility & Transportation'), ('REAL_ESTATE', 'Real Estate & PropTech'), ('MEDIA', 'Media & Entertainment'), ('HR_TECH', 'HR & Recruitment'), ('MARKETING', 'Marketing & Advertising'), ('LOGISTICS', 'Logistics & Supply Chain'), ('FOOD', 'FoodTech'), ('CREAECON', 'Creator Economy'), ('OTHER', 'Other')], default='ENT_SOFT', max_length=20, verbose_name='Industria'),
        ),
    ]
