# Generated by Django 5.2.4 on 2025-07-05 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0002_companies_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipoffers',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='internship_offers', to='internships.companies', verbose_name='Empresa'),
        ),
    ]
