# Generated by Django 5.2.4 on 2025-07-05 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0003_internshipoffers_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipoffers',
            name='banner',
            field=models.ImageField(blank=True, default=1, help_text='Imagen banner para cada oferta que se muestre en el dashboard', upload_to='internship_banners/', verbose_name='Banner de la oferta'),
        ),
    ]
