# Generated by Django 5.2.4 on 2025-07-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0004_internshipoffers_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipoffers',
            name='banner',
            field=models.ImageField(help_text='Imagen banner para cada oferta que se muestre en el dashboard', upload_to='internship_banners/', verbose_name='Banner de la oferta'),
        ),
    ]
